name: Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'extracted_diagrams/**', 'tools/**' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate documentation
      run: |
        python3 tools/generate_report.py
    
    - name: Verify diagrams
      run: |
        python3 tools/quick_mermaid_check.py
    
    - name: Commit documentation updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ extracted_diagrams/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update documentation and diagrams"
